---
# file: roles/monitoring/tasks/graylog.yml
- name: configure rsyslog 
  copy:
    content: "*.* @@{{ graylog_ip }}:{{ graylog_port }};RSYSLOG_SyslogProtocol23Format"
    dest: "/etc/rsyslog.d/90-graylog.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
