---
# file: roles/app/tasks/git.yml
- name: create application user
  user:
    name: "{{ application.username }}"
    password: "{{ application.password }}"
    shell: /bin/bash
    state: present
- name: install git
  apt:
    name: git
    state: latest
- name: clone the application's git repository
  git:
    repo: "{{ git.repository.application }}"
    dest: "/var/www/{{ application.name }}/"
    force: yes
- name: reassign application folder ownership to application user
  file:
    path: "/var/www/{{ application.name }}/"
    owner: "{{ application.username }}"
    group: "{{ application.username }}"
    recurse: yes
- name: create database.yml and secrets.yml
  copy:
    src: "{{ item }}"
    dest: "{{ application.base_dir }}/{{ application.name }}/config/{{ item }}"
    owner: "{{ application.username }}"
    group: "{{ application.username }}"
    mode: 0600
    force: yes
  with_items: ['database.yml', 'secrets.yml']
- name: create devise.rb
  copy:
    src: "{{ item }}"
    dest: "{{ application.base_dir }}/{{ application.name }}/config/initializers/{{ item }}"
    owner: "{{ application.username }}"
    group: "{{ application.username }}"
    mode: 0600
    force: yes
  with_items: 'devise.rb'
- name: execute rake secret
  shell: "/home/{{ application.username }}/.rbenv/versions/{{ application.ruby_version }}/bin/bundle exec rake secret"
  args:
    chdir: "/var/www/{{ application.name }}/"
  register: rake_secret
  become: yes
  become_user: "{{ application.username }}"
- name: set secret_key_base for devise.rb
  replace:
    path: "{{ application.base_dir }}/{{ application.name }}/config/initializers/devise.rb"
    regexp: '^(\s+)config.secret_key = ENV\[\"SECRET_KEY_BASE\"\]'
    replace: "\t\t\tconfig.secret_key = {{ rake_secret.stdout }}"
