---
# file: roles/db/tasks/postgresql.yml
- name: install postgresql
  apt:
    name: "{{ item }}"
    state: latest
  with_items: ['postgresql', 'postgresql-contrib', 'libpq-dev', 'python-psycopg2']
- name: make sure postgresql is running and enabled on startup
  service:
    name: postgresql
    state: started
    enabled: yes
- name: create the application database user
  postgresql_user:
    name: "{{ database.username }}"
    password: "{{ database.password }}"
    role_attr_flags: CREATEDB,LOGIN
    state: present
  become: yes
  become_user: postgres
