---
# file: roles/web/tasks/git.yml
- name: create application users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: /bin/bash
    state: present
  with_items: 
    - "{{ application.nodejs }}"
    - "{{ application.ruby }}"
- name: install git
  apt:
    name: git
    state: latest
- name: clone the application git repositories
  git:
    repo: "{{ item.repository }}"
    dest: "/var/www/{{ item.name }}/"
    force: yes
  with_items: 
    - "{{ application.nodejs }}"
    - "{{ application.ruby }}"
  notify: restart nginx
- name: reassign application folder ownership to application users
  file:
    path: "/var/www/{{ item.name }}/"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    recurse: yes
  with_items: 
    - "{{ application.nodejs }}"
    - "{{ application.ruby }}"
- name: modify access permissions for application config and db folders
  file:
    path: "/var/www/{{ application.ruby.name }}/{{ item }}"
    mode: 0700
  with_items: ['config', 'db']
- name: create database.yml and secrets.yml
  copy:
    src: "{{ item }}"
    dest: "{{ application.base_dir }}/{{ application.ruby.name }}/config/{{ item }}"
    owner: "{{ application.ruby.username }}"
    group: "{{ application.ruby.username }}"
    mode: 0600
    force: yes
  with_items: ['database.yml', 'secrets.yml']
- name: create devise.rb
  template:
    src: "{{ item }}"
    dest: "{{ application.base_dir }}/{{ application.ruby.name }}/config/initializers/{{ item }}"
    owner: "{{ application.ruby.username }}"
    group: "{{ application.ruby.username }}"
    mode: 0600
    force: yes
  with_items: 'devise.rb'
