---
# file: roles/web/tasks/rails.yml
- name: install rails
  shell: "/home/{{ application.ruby.username }}/.rbenv/versions/{{ application.ruby.version }}/bin/gem install rails"
  become: yes
  become_user: "{{ application.ruby.username }}"
- name: rehash rbenv
  shell: "/home/{{ application.ruby.username }}/.rbenv/bin/rbenv rehash"
  become: yes
  become_user: "{{ application.ruby.username }}"
