---
# file: roles/common/tasks/users.yml
- name: create users
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    state: present
  with_items: "{{ users }}"
- name: create sudoers
  copy:
    content: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ item.sudoers }}"
    owner: root
    group: root
    mode: 0440
  with_items: "{{ users }}"
- name: add ssh keys
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ users }}"
- name: disable password authentication through ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
- name: disable root login through ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
