---
# file: roles/web/defaults/main.yml
server:
  name:"{{ ansible_default_ipv4.address }}"
  port: 443
certificate:
  common: authority.vandelayindustries.com
  passphrase: self_signed_certificate_passphrase
