---
# file: roles/monitoring/handlers/main.yml
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
- name: restart zabbix agent
  service:
    name: zabbix-agent
    state: restarted
